name: deploy
on:
  push:
    branches:
      - master
      - int

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: ssh ubuntu@${{secrets.UWPATH_IP}} --i ${{secrets.UWPATH_PRIVATE_KEY}}
      - run: echo "success"
